/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiAesthetic;

/**
 *
 * @author Daniel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUDFrame = new javax.swing.JFrame();
        PanelCrud = new javax.swing.JPanel();
        TabbedDeOkis = new javax.swing.JTabbedPane();
        CrearTp = new javax.swing.JPanel();
        ListarTP = new javax.swing.JPanel();
        EliminarTP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuPanelPrincipal = new javax.swing.JPanel();
        MenuTextito = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CRUD = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        PanelCrud.setBackground(new java.awt.Color(0, 37, 125));
        PanelCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedDeOkis.setBackground(new java.awt.Color(0, 0, 102));

        CrearTp.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout CrearTpLayout = new javax.swing.GroupLayout(CrearTp);
        CrearTp.setLayout(CrearTpLayout);
        CrearTpLayout.setHorizontalGroup(
            CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        CrearTpLayout.setVerticalGroup(
            CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        TabbedDeOkis.addTab("Crear", CrearTp);

        ListarTP.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout ListarTPLayout = new javax.swing.GroupLayout(ListarTP);
        ListarTP.setLayout(ListarTPLayout);
        ListarTPLayout.setHorizontalGroup(
            ListarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        ListarTPLayout.setVerticalGroup(
            ListarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        TabbedDeOkis.addTab("Listar", ListarTP);

        EliminarTP.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout EliminarTPLayout = new javax.swing.GroupLayout(EliminarTP);
        EliminarTP.setLayout(EliminarTPLayout);
        EliminarTPLayout.setHorizontalGroup(
            EliminarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        EliminarTPLayout.setVerticalGroup(
            EliminarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        TabbedDeOkis.addTab("Eliminar", EliminarTP);

        PanelCrud.add(TabbedDeOkis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 260));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CRUD");
        PanelCrud.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        javax.swing.GroupLayout CRUDFrameLayout = new javax.swing.GroupLayout(CRUDFrame.getContentPane());
        CRUDFrame.getContentPane().setLayout(CRUDFrameLayout);
        CRUDFrameLayout.setHorizontalGroup(
            CRUDFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        CRUDFrameLayout.setVerticalGroup(
            CRUDFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanelPrincipal.setBackground(new java.awt.Color(40, 131, 137));
        MenuPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuTextito.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        MenuTextito.setForeground(new java.awt.Color(255, 255, 255));
        MenuTextito.setText("Menu");
        MenuPanelPrincipal.add(MenuTextito, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 28, -1, 40));

        jButton1.setBackground(new java.awt.Color(0, 91, 73));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        MenuPanelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 154, 53));

        CRUD.setBackground(new java.awt.Color(0, 91, 73));
        CRUD.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        CRUD.setText("CRUD");
        CRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CRUDMouseClicked(evt);
            }
        });
        CRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDActionPerformed(evt);
            }
        });
        MenuPanelPrincipal.add(CRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 154, 53));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 87, 89));
        MenuPanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 310, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRUDActionPerformed

    private void CRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRUDMouseClicked
        //BOTON DEL CRUD
        CRUDFrame.setVisible(true);
        CRUDFrame.pack();
    }//GEN-LAST:event_CRUDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CRUD;
    private javax.swing.JFrame CRUDFrame;
    private javax.swing.JPanel CrearTp;
    private javax.swing.JPanel EliminarTP;
    private javax.swing.JPanel ListarTP;
    private javax.swing.JPanel MenuPanelPrincipal;
    private javax.swing.JLabel MenuTextito;
    private javax.swing.JPanel PanelCrud;
    private javax.swing.JTabbedPane TabbedDeOkis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
