/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiAesthetic;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Daniel
 */
public class Main extends javax.swing.JFrame {
ArrayList computadoras = new ArrayList();
static Scanner lea = new Scanner(System.in);
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUDFrame = new javax.swing.JFrame();
        PanelCrud = new javax.swing.JPanel();
        CrearLaptop = new javax.swing.JTabbedPane();
        CrearTp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ip = new javax.swing.JTextField();
        mascara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pantalla = new javax.swing.JTextField();
        targetagrafica = new javax.swing.JCheckBox();
        CreandoLaptop = new javax.swing.JButton();
        ListarTP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listitaCRUD = new javax.swing.JTextArea();
        EliminarTP = new javax.swing.JPanel();
        BotonEliminar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        IpE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mascaraE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hostE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        capRam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        capAlma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tipoAlma = new javax.swing.JTextField();
        TGraficaEscri = new javax.swing.JCheckBox();
        CrearEscritorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MenuPanelPrincipal = new javax.swing.JPanel();
        MenuTextito = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CRUD = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        PanelCrud.setBackground(new java.awt.Color(0, 37, 125));
        PanelCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearLaptop.setBackground(new java.awt.Color(0, 0, 102));
        CrearLaptop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CrearLaptopStateChanged(evt);
            }
        });

        CrearTp.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ingrese la mascara");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ingrese la IP");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ingrese el host");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Ingrese la marca");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Ingrese la def. pantalla");

        targetagrafica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        targetagrafica.setText("Targeta Grafica");
        targetagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetagraficaActionPerformed(evt);
            }
        });

        CreandoLaptop.setText("Crear");
        CreandoLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreandoLaptopMouseClicked(evt);
            }
        });
        CreandoLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreandoLaptopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearTpLayout = new javax.swing.GroupLayout(CrearTp);
        CrearTp.setLayout(CrearTpLayout);
        CrearTpLayout.setHorizontalGroup(
            CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(host, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mascara, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(targetagrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreandoLaptop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        CrearTpLayout.setVerticalGroup(
            CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTpLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mascara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetagrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrearTpLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CreandoLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        CrearLaptop.addTab("Crear Laptop", CrearTp);

        ListarTP.setBackground(new java.awt.Color(0, 0, 102));

        listitaCRUD.setColumns(20);
        listitaCRUD.setRows(5);
        jScrollPane1.setViewportView(listitaCRUD);

        javax.swing.GroupLayout ListarTPLayout = new javax.swing.GroupLayout(ListarTP);
        ListarTP.setLayout(ListarTPLayout);
        ListarTPLayout.setHorizontalGroup(
            ListarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        ListarTPLayout.setVerticalGroup(
            ListarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListarTPLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CrearLaptop.addTab("Listar", ListarTP);

        EliminarTP.setBackground(new java.awt.Color(0, 0, 102));

        BotonEliminar.setBackground(new java.awt.Color(204, 0, 0));
        BotonEliminar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout EliminarTPLayout = new javax.swing.GroupLayout(EliminarTP);
        EliminarTP.setLayout(EliminarTPLayout);
        EliminarTPLayout.setHorizontalGroup(
            EliminarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarTPLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(EliminarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        EliminarTPLayout.setVerticalGroup(
            EliminarTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarTPLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        CrearLaptop.addTab("Eliminar", EliminarTP);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese la mascara");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ingrese la IP");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Ingrese el host");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Ingrese la capacidad RAM");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Capacidad Almacenamiento");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tipo de Almacenamiento");

        TGraficaEscri.setText("Tarjeta grafica");
        TGraficaEscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TGraficaEscriActionPerformed(evt);
            }
        });

        CrearEscritorio.setText("Crear");
        CrearEscritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearEscritorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mascaraE)
                        .addComponent(IpE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hostE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(capRam)))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capAlma)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoAlma)
                    .addComponent(TGraficaEscri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IpE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capAlma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mascaraE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoAlma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hostE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capRam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TGraficaEscri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CrearEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CrearLaptop.addTab("Crear  PC Escritorio", jPanel1);

        PanelCrud.add(CrearLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 460, 380));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CRUD");
        PanelCrud.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        javax.swing.GroupLayout CRUDFrameLayout = new javax.swing.GroupLayout(CRUDFrame.getContentPane());
        CRUDFrame.getContentPane().setLayout(CRUDFrameLayout);
        CRUDFrameLayout.setHorizontalGroup(
            CRUDFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        CRUDFrameLayout.setVerticalGroup(
            CRUDFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCrud, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanelPrincipal.setBackground(new java.awt.Color(40, 131, 137));
        MenuPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuTextito.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        MenuTextito.setForeground(new java.awt.Color(255, 255, 255));
        MenuTextito.setText("Menu");
        MenuPanelPrincipal.add(MenuTextito, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 28, -1, 40));

        jButton1.setBackground(new java.awt.Color(0, 91, 73));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        MenuPanelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 154, 53));

        CRUD.setBackground(new java.awt.Color(0, 91, 73));
        CRUD.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        CRUD.setText("CRUD");
        CRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CRUDMouseClicked(evt);
            }
        });
        CRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDActionPerformed(evt);
            }
        });
        MenuPanelPrincipal.add(CRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 154, 53));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 87, 89));
        MenuPanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 310, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRUDActionPerformed

    private void CRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRUDMouseClicked
        //BOTON DEL CRUD
        CRUDFrame.setVisible(true);
        CRUDFrame.pack();
    }//GEN-LAST:event_CRUDMouseClicked

    private void targetagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetagraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetagraficaActionPerformed

    private void CreandoLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreandoLaptopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CreandoLaptopMouseClicked

    private void CreandoLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreandoLaptopActionPerformed
        String ip= Ip.getText();
        String mascaras= mascara.getText();
        String hosting= host.getText();
        String marcas= marca.getText();
        String definicion= pantalla.getText();
        boolean tarjeta= targetagrafica.isSelected();
        
        Laptop laptopCompu= new Laptop(ip,mascaras,hosting,marcas,definicion,tarjeta);
        computadoras.add(laptopCompu);
        
        Ip.setText("");
        mascara.setText("");
        host.setText("");
        marca.setText("");
        pantalla.setText("");
        
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        jComboBox1.setModel(m);
        for (Object comp : computadoras) {
            m.addElement(comp);
        }
        jComboBox1.setModel(m);
    }//GEN-LAST:event_CreandoLaptopActionPerformed

    private void CrearLaptopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CrearLaptopStateChanged
        //Esto es para listar
        if (CrearLaptop.getSelectedIndex() == 1){
            listitaCRUD.setText("");
            for (Object Compus: computadoras) {
                listitaCRUD.append(" "+computadoras.indexOf(Compus)+"-. "+Compus+"\n");
            }
        }
    }//GEN-LAST:event_CrearLaptopStateChanged

    private void BotonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseClicked
        //Esto es para borrar
        computadoras.remove((Object) (jComboBox1.getSelectedItem()));
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        jComboBox1.setModel(m);
        for (Object comp : computadoras) {
            m.addElement(comp);
        }
        jComboBox1.setModel(m);
    }//GEN-LAST:event_BotonEliminarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //EALE
        System.out.println("ingrese el hostname deseado: ");
        lea = new Scanner(System.in);
        String hostname = lea.nextLine();
        for (Object computadora : computadoras) {
            if (((PC) (computadora)).getHosting().equals(hostname)) {
                System.out.print(hostname + "#");

                lea = new Scanner(System.in);
                String comando = lea.nextLine();

                if (comando.contains("ping_")) {
                    String[] arrOfStr = comando.split("_", 2);
                    for (Object computadoraa : computadoras) {
                        if (((PC) (computadoraa)).getIp().equals(arrOfStr[1]) && ((PC) (computadoraa)).getMascara().equals(((PC) (computadora)).getMascara())) {
                            System.out.println("Pinging to " + ((PC) (computadora)).getIp() + "with 32 bits of data:");
                            for (int i = 0; i < 4; i++) {
                                System.out.println("Reply from " + arrOfStr[1] + ": bytes=32 time=37ms TTL=46");
                            }
                            System.out.println("Ping statistics for " + arrOfStr[1]);
                            System.out.println("     Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)");
                        } else if (((PC) (computadoraa)).getIp().equals(arrOfStr[1]) && !((PC) (computadoraa)).getMascara().equals(((PC) (computadora)).getMascara())) {
                            System.out.println("Pinging to " + ((PC) (computadora)).getIp() + "with 32 bits of data:");
                            for (int i = 0; i < 4; i++) {
                                System.out.println("Reply from " + arrOfStr[1] + ": Destination host unreachable");
                            }
                            System.out.println("Ping statistics for " + arrOfStr[1]);
                            System.out.println("     Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)");
                        }

                        if (!((PC) (computadoraa)).getIp().equals(arrOfStr[1]) && !((PC) (computadoraa)).getMascara().equals(((PC) (computadora)).getMascara())) {
                            System.out.println("Pinging to " + ((PC) (computadora)).getIp() + "with 32 bits of data:");
                            for (int i = 0; i < 4; i++) {
                                System.out.println("Request timed out");
                            }
                            System.out.println("Ping statistics for " + arrOfStr[1]);
                            System.out.println("     Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)");
                        }
                    }

                    }else if (comando.contains("show")) {
                     System.out.println(((PC) (computadora)).getIp()+ "    " + ((PC) (computadora)).getMascara());
                } else {
                    System.out.println("CONSOLE CLOSED");
                    System.out.print(hostname + "#");

                }

                }
            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void TGraficaEscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TGraficaEscriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TGraficaEscriActionPerformed

    private void CrearEscritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearEscritorioMouseClicked
        //Se me olvido esto
        String ips= IpE.getText();
        String mascarass= mascaraE.getText();
        String hostings= hostE.getText();
        String capaRam= capRam.getText();
        String capaAlm= capAlma.getText();
        String tipoAlm= tipoAlma.getText();
        boolean tarjetaG= TGraficaEscri.isSelected();
        
        Escritorio escritorio = new Escritorio (ips,mascarass,hostings,capaRam,capaAlm,tipoAlm,tarjetaG);
        computadoras.add(escritorio);
        
        IpE.setText("");
        mascaraE.setText("");
        hostE.setText("");
        capRam.setText("");
        capAlma.setText("");
        tipoAlma.setText("");
        
    }//GEN-LAST:event_CrearEscritorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton CRUD;
    private javax.swing.JFrame CRUDFrame;
    private javax.swing.JButton CreandoLaptop;
    private javax.swing.JButton CrearEscritorio;
    private javax.swing.JTabbedPane CrearLaptop;
    private javax.swing.JPanel CrearTp;
    private javax.swing.JPanel EliminarTP;
    private javax.swing.JTextField Ip;
    private javax.swing.JTextField IpE;
    private javax.swing.JPanel ListarTP;
    private javax.swing.JPanel MenuPanelPrincipal;
    private javax.swing.JLabel MenuTextito;
    private javax.swing.JPanel PanelCrud;
    private javax.swing.JCheckBox TGraficaEscri;
    private javax.swing.JTextField capAlma;
    private javax.swing.JTextField capRam;
    private javax.swing.JTextField host;
    private javax.swing.JTextField hostE;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea listitaCRUD;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField mascara;
    private javax.swing.JTextField mascaraE;
    private javax.swing.JTextField pantalla;
    private javax.swing.JCheckBox targetagrafica;
    private javax.swing.JTextField tipoAlma;
    // End of variables declaration//GEN-END:variables
}
